# PostgresSQL Connection Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pw5_packovery?stringtype=unspecified
quarkus.datasource.username=postgres
quarkus.datasource.password=${PG_PASSWORD}

# MongoDB Connection Configuration
quarkus.mongodb.connection-string=mongodb+srv://alessianicolini2005_db_user:${MONGO_PASSWORD}@pw5.nube9wd.mongodb.net/
quarkus.mongodb.database=packoverydb
quarkus.mongodb.dns.lookup-timeout=200S
quarkus.mongodb.dns.log-activity=true
quarkus.naming.enable-jndi=true

# Jackson Configuration
quarkus.jackson.date-format=iso8601
quarkus.jackson.serialization.write-dates-as-timestamps=false

# CORS Configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-allow-credentials=true

# JWT Configuration
mp.jwt.verify.issuer=packovery-backend-jwt