# PostgresSQL Connection Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://172.17.3.150:5432/pw5_packovery?stringtype=unspecified
quarkus.datasource.username=postgres
quarkus.datasource.password=${PG_PASSWORD}
quarkus.datasource.devservices.enabled=false
quarkus.datasource.jdbc.additional-jdbc-properties.stringtype=unspecified

# MongoDB Connection Configuration
quarkus.mongodb.connection-string=mongodb+srv://alessianicolini2005_db_user:${MONGO_PASSWORD}@pw5.nube9wd.mongodb.net/
quarkus.mongodb.database=packoverydb
quarkus.mongodb.dns.lookup-timeout=200S
quarkus.mongodb.dns.log-activity=true
quarkus.naming.enable-jndi=true
quarkus.devservices.enabled=false

# Mailer Configuration
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${EMAIL_ADDRESS}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=465
quarkus.mailer.tls=true
quarkus.mailer.username=${EMAIL_USERNAME}
quarkus.mailer.password=${EMAIL_PASSWORD}
quarkus.mailer.mock=false

# Jackson Configuration
quarkus.jackson.date-format=iso8601
quarkus.jackson.serialization.write-dates-as-timestamps=false

# CORS Configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-allow-credentials=true

# JWT Configuration
mp.jwt.verify.issuer=packovery-backend-jwt

# Logging Configuration
quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
quarkus.log.file.json=true
